apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  namespace: build2
  annotations:
    build.knative.dev/docker-0: https://index.docker.io/v1/  # https://gcr.io for google container registry
type: kubernetes.io/basic-auth
stringData:
  username: {username}  # no need for base64 encoding
  password: {password}